name: dartflow
description: A strictly typed, event-driven DAG orchestration framework for Dart. Wire immutable events to validated workflows, get typed results back as streams.
version: 0.0.1
homepage: https://github.com/2000023946/DartFlow

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0